export const QUOTES_STATUSES = {
  PENDING: 0,
  OPEN: 1,
  WAITING: 2,
  REJECTED: 3,
  CANCELED: 4,
  EXECUTED: 5,
  EXPIRED: 6,
  PENDINGCANCEL: 7,
  PENDINGREPLACE: 8,
  PENDINGEXPIRE: 9,
  PENDINGREJECT: 10,
  RISKREJECTED: 11,
  PENDINGRISKREJECT: 12
}
